config/routes.rb
IndieTheater::Application.routes.draw do
  devise_for :customers, :controllers => { :omniauth_callbacks => "customers/omniauth_callbacks" }
  devise_for :admins

  root :to => "pages#index"

  resources :pages, :only => [:index] 
  match '/about' => 'pages#about'
  match '/contact' => 'pages#contact'
  
  resources :customers
  resources :admins, :except => [:show]
  resources :movies
  resources :showtimes, :only => [:index, :show]
  resources :orders, :only => [:show, :create, :destroy]
  resources :cart_items, :only => [:create, :destroy]
  resources :reviews, :except => [:index, :show]
  resources :comments
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  before_filter :authenticate_admin!, :only => [:new, :create, :edit, :update, :destory]
  
  def index
    now = DateTime.now
    @now_playing = Movie.where("opening_date <= ?", now).online
    @coming_soon = Movie.where("opening_date > ?", now).online
  end
  
  def show
    @movie = Movie.find(params[:id])
    now = DateTime.now
    
    @now_playing = Movie.where("opening_date <= ?", now).online
    @coming_soon = Movie.where("opening_date > ?", now).online
    
    @comment = Comment.new
    @comments = @movie.comments.order("id").all
  end
  
  def new
    @movie = Movie.new
    @movie.online = false
    @movie.three_d = false
  end
  
  def create
    @movie = Movie.new(params[:movie])
    
    if @movie.save
      redirect_to movie_url(@movie)
    else
      render :new
    end
  end
  
  def edit
    @movie = Movie.find(params[:id])
  end
  
  def update
    @movie = Movie.find(params[:id])
    
    if @movie.update_attributes(params[:movie])
      redirect_to movie_url(@movie)
    else
      render :edit
    end
  end
  
  def destroy
    Movie.find(params[:id]).destroy
    redirect_to :action => 'index'
  end
end

app/views/movies/_form.html.erb
<div class="content group">
	<h1 class="main-header">Movie Form</h1>
	
	<%= nested_form_for(@movie) do |f| %>
	
	<div><%= f.label :title %></div>
	<div><%= f.text_field :title %></div>
	
	<div><%= f.label :description %></div>
	<div><%= f.text_area :description %></div>
	
	<div><%= f.label :rating_id, "Rating" %></div>
	<div><%= collection_select(:movie, :rating_id, Rating.all, :id, :value) %></div>
	
	<div><%= f.label :opening_date %></div>
	<div><%= f.date_select :opening_date %></div>
	
	<div><%= f.label :starring %></div>
	<div><%= f.text_field :starring %></div>
	
	<div><%= f.label :director %></div>
	<div><%= f.text_field :director %></div>
	
	<div><%= f.label :runtime %></div>
	<div><%= f.text_field :runtime %></div>
	
	<div><%= f.label :released_by %></div>
	<div><%= f.text_field :released_by %></div>
	
	<div><div>Genres:</div>  
		<% Genre.all.each do |genre| %>
		<label>
      
      <input 
        type="checkbox" 
        name="movie[genre_ids][]" 
        value="<%= genre.id %>" 
        <%= "checked" if @movie.genres.include?(genre) %>>
      
      <%= genre.name %>  
    </label> 
		<% end %>
	</div>
	
	<div> 3D? <%= f.label :three_d, "False", :value => false %>
	<%= f.radio_button :three_d, false %>
	
	<%= f.label :three_d, "True", :value => true %>
	<%= f.radio_button :three_d, true %></div>
	
	<div><%= f.label :poster %></div>
	<div><%= f.file_field :poster %></div>
	
	<div><%= f.label :trailer %></div>
	<div><%= f.text_field :trailer %></div>	
	
	<div> Online? <%= f.label :online, "False", :value => false %>
	<%= f.radio_button :online, false %>
	
	<%= f.label :online, "True", :value => true %>
	<%= f.radio_button :online, true %></div>
	
	<%= f.fields_for :showtimes do |showtime_form| %>
		<div><%= showtime_form.datetime_select :time %></div>
		<div>Screen: <%= showtime_form.collection_select(:screen_id, Screen.all, :id, :id) %></div>
	  <%= showtime_form.link_to_remove "Remove this showtime" %>
	<% end %>
	<p><%= f.link_to_add "Add a showtime", :showtimes %></p>		
	
	<%= f.submit %>
	
	<% end %>

</div>

app/views/movies/_list.html.erb
	<section class="content-left">
  
    <header class="content-header">
      <h2>Now Playing</h2>
    </header>
  
    <div class="posts">
			
			<% @now_playing.each do |n| %>
      
			<article class="post">
        <header class="group">
    
          <div class="post-thumb">
            <%= link_to (image_tag n.poster.url(:small)), movie_url(n) %>
          </div>
    
          <div class="post-info">
            <h3><%= link_to "#{n.full_title} (#{n.rating.value})", movie_url(n) %></h3>
            <p>
							<strong>Runtime:</strong> <%= "#{n.runtime} mins." %><br>
							<strong>Director:</strong> <%= n.director %><br>
							<strong>Genres:</strong> <% n.genres.each do |g| %> <%= g.name %> <% end %><br>
							<strong>Starring:</strong> <%= n.starring %>
						</p>
          </div>
    
        </header>
      </article>
			
			<% end %>
    	
    </div>
  </section>
	
  <section class="content-right">
  
    <header class="content-header">
      <h2>Coming Soon</h2>
    </header>
  
    <div class="posts">
    	
			<% @coming_soon.each do |c| %>
			
      <article class="post">
        <header class="group">
    
          <div class="post-thumb">
            <%= link_to (image_tag c.poster.url(:small)), movie_url(c) %>
          </div>
    
          <div class="post-info">
            <h3><%= link_to c.full_title, movie_url(c) %></h3>
            <p>
							<strong>Opens: </strong><%= c.opening_date.strftime('%A, %B %e') %><br>
							<strong>Runtime:</strong> <%= "#{c.runtime} mins." %><br>
							<strong>Director:</strong>  <%= "#{c.director}" %><br>
							<strong>Genres:</strong> <% c.genres.each do |g| %> <%= g.name %> <% end %><br>
							<strong>Starring:</strong> <%= "#{c.starring}" %>
						</p>
          </div>
    
        </header>
      </article>
			
			<% end %>
			
    </div>
  
  </section>

app/views/movies/index.html.erb
<div class="content group">	
	<% if admin_signed_in? %>
	
	<div class="online content-left">
		<h1 class="main-header">Online</h1>
			<ul>
			<% Movie.online.reverse.each do |movie| %>
			
			<li><%= link_to "#{movie.title}", movie_url(movie) %>
					<%= button_to "Edit", edit_movie_url(movie), :method => "get", :form_class => "edit-button" %>
					<%= button_to "Delete", movie_url(movie), :method => "delete", :form_class => "delete-button" %></li><br>
		
			<% end %>
			</ul>
		</div>
	
	<div class="offline content-right">
		<h1 class="main-header">Offline</h1>	
			<ul>
			<% Movie.offline.reverse.each do |movie| %>
		
			<li><%= link_to "#{movie.title}", movie_url(movie) %>
					<%= button_to "Edit", edit_movie_url(movie), :method => "get", :form_class => "edit-button" %>
					<%= button_to "Delete", movie_url(movie), :method => "delete", :form_class => "delete-button" %></li>
	
			<% end %>
		</ul>
	</div>
		
	<% else %>
	<section class="content-left">
  
    <header class="content-header">
      <h2>Now Playing</h2>
    </header>
  
    <div class="posts">
			
			<% @now_playing.each do |n| %>
      
			<article class="post">
        <header class="group">
    
          <div class="post-thumb">
            <%= link_to (image_tag n.poster.url(:small)), movie_url(n) %>
          </div>
    
          <div class="post-info">
            <h3><%= link_to "#{n.full_title} (#{n.rating.value})", movie_url(n) %></h3>
            <p>
							<strong>Runtime:</strong> <%= "#{n.runtime} mins." %><br>
							<strong>Director:</strong> <%= n.director %><br>
							<strong>Genres:</strong> <% n.genres.each do |g| %> <%= g.name %> <% end %><br>
							<strong>Starring:</strong> <%= n.starring %>
						</p>
          </div>
    
        </header>
      </article>
			
			<% end %>
    	
    </div>
  </section>
	
  <section class="content-right">
  
    <header class="content-header">
      <h2>Coming Soon</h2>
    </header>
  
    <div class="posts">
    	
			<% @coming_soon.each do |c| %>
			
      <article class="post">
        <header class="group">
    
          <div class="post-thumb">
            <%= link_to (image_tag c.poster.url(:small)), movie_url(c) %>
          </div>
    
          <div class="post-info">
            <h3><%= link_to c.full_title, movie_url(c) %></h3>
            <p>
							<strong>Opens: </strong><%= c.opening_date.strftime('%A, %B %e') %><br>
							<strong>Runtime:</strong> <%= "#{c.runtime} mins." %><br>
							<strong>Director:</strong>  <%= "#{c.director}" %><br>
							<strong>Genres:</strong> <% c.genres.each do |g| %> <%= g.name %> <% end %><br>
							<strong>Starring:</strong> <%= "#{c.starring}" %>
						</p>
          </div>
    
        </header>
      </article>
			
			<% end %>
			
    </div>
  
  </section>
	<% end %>
</div>

app/views/movies/show.html.erb
<div class="content group">
  <section class="content-movie">
		
		<header class="vital-info group">
			<h2 class="movie-title"><%= "#{@movie.full_title} (#{@movie.rating.value})" %>
															<% if admin_signed_in? %>
																<%= link_to "Edit", edit_movie_url(@movie) %>
																<% end %>
															</h2>
			<p class="release-date"><strong>Release Date: </strong> <%= @movie.opening_date.to_date %></p>
		</header>
		
    <article class="post">
      <header class="group">
				
        <div class="movie-media group">
					<div class="movie-poster">
						<%= link_to (image_tag @movie.poster.url(:medium)), movie_url(@movie) %>
					</div>

					<div class="movie-trailer">					
						<iframe width="560" height="310" src="<%= @movie.trailer %>" frameborder="0"></iframe>
					</div>
				</div>
  
        <div class="movie-text">
          <p>
						<% if @now_playing.include?(@movie) %>
							<p><%= display_score(@movie) %>
								<% if customer_signed_in? %>
									<%= link_to("Add Rating", new_review_url(:movie_id => @movie.id)) unless current_customer.movies.include?(@movie)  %>
								<% end %>
							</p>
						<% end %>
						<%= @movie.description %> 
					</p>
					<ul>
						<li><strong>Starring:</strong> <%= @movie.starring %></li>
						<li><strong>Director:</strong> <%= @movie.director %></li>
						<li><strong>Runtime:</strong> <%= "#{@movie.runtime} mins." %></li>
						<li><strong>Released By:</strong> <%= @movie.released_by %></li>
					</ul>				
        </div>
				
				<div class="movie-comments">
					<%= render "/comments/comments" %>
				</div>
  
      </header>
    </article>
					
	</section>
	
</div>