config/routes.rb
IndieTheater::Application.routes.draw do
  devise_for :customers, :controllers => { :omniauth_callbacks => "customers/omniauth_callbacks" }
  devise_for :admins

  root :to => "pages#index"

  resources :pages, :only => [:index] 
  match '/about' => 'pages#about'
  match '/contact' => 'pages#contact'
  
  resources :customers
  resources :admins, :except => [:show]
  resources :movies
  resources :showtimes, :only => [:index, :show]
  resources :orders, :only => [:show, :create, :destroy]
  resources :cart_items, :only => [:create, :destroy]
  resources :reviews, :except => [:index, :show]
  resources :comments
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]         

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :order_ids, :cart_item_ids, :provider, :uid, :name
  # attr_accessible :title, :body
  
  has_many :orders
  has_many :tickets, :through => :orders
  has_many :cart_items
  has_many :reviews
  has_many :movies, :through => :reviews
  has_many :comments
  
  
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    customer = Customer.where(:provider => auth.provider, :uid => auth.uid).first
    unless customer
      customer = Customer.create(provider:auth.provider,
                           uid:auth.uid,
                           email:auth.info.email,
                           password:Devise.friendly_token[0,20]
                           )
    end
    customer
  end
  
  def self.new_with_session(params, session)
    super.tap do |customer|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        customer.email = data["email"] if customer.email.blank?
      end
    end
  end
end

app/controllers/customers/omniauth_callbacks_controller.rb
class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
     # You need to implement the method below in your model (e.g. app/models/customer.rb)
     @customer = Customer.find_for_facebook_oauth(request.env["omniauth.auth"], current_customer)

     if @customer.persisted?
       sign_in_and_redirect @customer, :event => :authentication #this will throw if @customer is not activated
       set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
     else
       session["devise.facebook_data"] = request.env["omniauth.auth"]
       redirect_to new_customer_registration_url
     end
   end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  
  before_filter :authenticate_customer!
  
  def show
    @customer = current_customer
    @cart_items = current_customer.cart_items
    @orders = current_customer.orders
    @order = Order.new
    @reviews = current_customer.reviews
  end
  
  def edit
    @customer = Customer.find(params[:id])
    
    unless @customer == current_customer
      redirect_to root_url
    end
  end
  
  def update
    @customer = Customer.find(params[:id])
    
    if @customer.update_attributes(params[:customer])
      redirect_to customer_url(@customer)
    else
      render :edit
    end
  end
  
  def destroy
    Customer.find(params[:id]).destroy
    redirect_to root_url
  end
end

app/views/customers/edit.html.erb
<div class="content group">
	<h1 class="main-header">My Account</h1>
	<div class="back-to-main"><%= link_to "Back to Main", customer_url(current_customer) %></div>
	
	<%= form_for(@customer) do |f| %>
	
	<div class="customer-label"><%= f.label :email %></div>
	<div><%= f.text_field :email %></div>
	
	<div class="customer-label"><%= f.label :password, "New Password" %></div>
	<div><%= f.password_field :password %></div>
	
	<div class="customer-label"><%= f.label :password_confirmation, "New Password Confirmation" %></div>
	<div><%= f.password_field :password_confirmation %></div>
		
	<div class="customer-label"><%= f.submit %></div>
	
	<% end %>
	
	<hr>
	
	<div class="cancel-form"><%= button_to "Delete My Account", customer_url(@customer), :method => "delete" %></div>

</div>

app/views/customers/show.html.erb
<div class="content group">
	<h1 class="main-header">My Account</h1><%= link_to "Update My Information", edit_customer_url, :method => "get", :class => "update-info" %><br><br> 
	<%= link_to("Sign Out", destroy_customer_session_url, :method => "delete") %><hr>
	
	<div>
		<h2 class="cart">Shopping Cart</h2>
		<ul>
			<% @cart_items.each do |item| %>
				<li class="item"><%= "#{item.quantity} tickets - #{item.showtime.movie.title} - #{item.showtime.time.strftime('%A, %b %d at %l:%M %p')}" %>
					<%= button_to "Place Order", orders_url(@order, :quantity => item.quantity, :showtime_id => item.showtime.id, :cart_item_id => item.id) %>
				<%= button_to "Remove From Cart", cart_item_url(item), :method => "delete" %></li>
			<% end %>
		</ul>
	</div><hr>

	<h2 class="orders">Reviews</h2>
		<ul>
			<% @reviews.each do |review| %>
				<li class="order"><%= link_to review.movie.title, edit_review_url(review) %></li>
			<% end %>
		</ul><hr>	
	
	<h2 class="orders">Orders</h2>
	<ul>
		<% @orders.each do |order| %>
			<li class="order"><%= link_to order.created_at.strftime('%B %d at %l:%M %p'), order_url(order) %></li>
		<% end %>
	</ul>	

</div>