config/routes.rb
IndieTheater::Application.routes.draw do
  devise_for :customers, :controllers => { :omniauth_callbacks => "customers/omniauth_callbacks" }
  devise_for :admins

  root :to => "pages#index"

  resources :pages, :only => [:index] 
  match '/about' => 'pages#about'
  match '/contact' => 'pages#contact'
  
  resources :customers
  resources :admins, :except => [:show]
  resources :movies
  resources :showtimes, :only => [:index, :show]
  resources :orders, :only => [:show, :create, :destroy]
  resources :cart_items, :only => [:create, :destroy]
  resources :reviews, :except => [:index, :show]
  resources :comments
end

app/views/pages/_sidebar.html.erb
<section class="content-sidebar">

  <div class="profile-picture">
		<%= link_to (image_tag "IncrediblesLogo.png"), root_url %>
  </div>

  <div class="profile-info">
    <h2>Indie Theater</h2>
    <p>
      0 Infinite Loop<br>
			Brooklyn, NY 11111<br>
      <strong>Phone</strong> (555) 555-5555
			<% if admin_signed_in? %>
				<ul>
					<li><%= link_to "Sign Out", destroy_admin_session_url, :method => "delete" %></li>
					<li><%= link_to "Add Movie", new_movie_url %></li>
					<li><%= link_to "Edit Movies", movies_url %></li>
					<% if current_admin.super %>
						<li><%= link_to "Create Admin", new_admin_url %></li>
						<li><%= link_to "All Admins", admins_url %></li>
					<% end %>
					
				</ul>
			<% end %>
    </p>
  </div>

</section>

app/views/pages/about.html.erb
<% cache do %>

	<div class="content group">
		<div class="static">

	  <h1 class="main-header">About</h1>

		<p class="static-text">This is <%= link_to "James Pothen's", "http://www.jamespothen.com", :target => "blank" %> capstone project for <%= link_to "App Academy", "http://www.appacademy.io/", :target => "blank" %>. It is built in Ruby on Rails, with Javascript and jQuery giving it some shine.</p>
	
		<h2 class="sub-header">Why a Movie Theater?</h2>
	
		<p class="static-text">Because local cinemas that show beautiful films should have beautiful websites.</p>
	
		<h2 class="sub-header">Noteworthy Features: </h2>
		<ul class="static-text static-list">
			<li>Facebook Login for painless registration</li>
			<li>jQuery-powered Carousel on the homepage</li>
			<li>Fast initial load thanks to a Heroku Pinger</li>
			<li>Caching for quick subsequent page loads</li>
			<li>Clever day of the week display on Showtimes</li>
		</ul>

		<h2 class="sub-header">Like What You See?</h2>
		
		<ol class="static-text">
			<li><%= link_to "Here's my resume.", "http://jamespothen.com/WebEngineer_JamesPothen_Online.pdf", :target => "blank" %> </li> 
			<li><%= link_to "Hire me!", "http://jamespothen.com/connect", :target => "blank" %></li>
		</ol>

		</div>
	</div>

<% end %>

app/views/pages/contact.html.erb
<% cache do %>
	<div class="content group">
		<div class="static">
		  <h1 class="main-header">Contact Us</h1>
	
			<p class="static-text">Phone: (555) 555-5555</p>
		</div>
	</div>
<% end %>

app/views/pages/index.html.erb
<% cache do %>
	<div class="content group">
	  <section class="content-sidebar">
  
			<%= render "pages/sidebar" %>
	
	  </section>
	  <section class="content-main">
  
	    <header class="content-header">
	      <h1>Film. Experienced.</h1>
	    </header>
  
	    <div class="posts" id="carousel">
				<ul>
					<li><%= link_to (image_tag "now_you_see_me.jpg"), "/movies/2" %></li>
					<li><%= link_to (image_tag "man-of-steel-henry-cavill5.jpg"), "/movies/3" %></li>
					<li><%= link_to (image_tag "the-internship.jpg"), "/movies/6" %></li>
				</ul>
			  <div id="carousel-nav">
			    <span class="first">&#9675;</span>
			    <span class="second">&#9675;</span>
			    <span class="third">&#9675;</span>
			  </div>		
	    </div>	
		
	  </section>
	</div>

	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>

	<script>
		var Carousel = (function(){
	
			var delay = 6000;
			var carousel = $("#carousel");
			var itemsHolder = carousel.find("> ul");
			var items = itemsHolder.find("> li");
			var itemWidth = items.first().width();
			var currentItem = -1;
			var timerId;
	
		  var firstButton = $("#carousel-nav > .first");
		  var secondButton = $("#carousel-nav > .second");	
			var thirdButton = $("#carousel-nav > .third");
	
			var init = function(){
				itemsHolder.css({"width": (items.length * itemWidth) + "px"});
				bind();
				start();
			}
	
		  var bind = function(){
		    firstButton.on("click", first);
		    secondButton.on("click", second);
		    thirdButton.on("click", third);
		  }
	
			var start = function(){
				loop();
				timerId = window.setInterval(loop, delay);
			}
	
			var stop = function(){
				if(timerId){
					window.clearInterval(timerId);
				}
			}
	
			var loop = function(){
				next();
			}
	
			var next = function(){
				currentItem++;
		
				if(currentItem == items.length){
					currentItem = 0;
				}
		
				move();
			};
	
			var previous = function(){
				currentItem--;
		
				if(currentItem <= 0){
					currentItem = items.length - 1;
				}
		
				move();
			}
	
			var move = function(){
				var leftPosition = currentItem * itemWidth * -1;
				itemsHolder.stop().animate({"left": leftPosition + "px"}, 1000);

				animateDots();
			}
	
			var animateDots = function(){
				firstButton.html("&#9679;");
				secondButton.html("&#9679;");
				thirdButton.html("&#9679;");
		
				if(currentItem == 0){
					firstButton.html("&#9675;");
				}
				else if(currentItem == 1){
					secondButton.html("&#9675;");
				}
				else{
					thirdButton.html("&#9675;");
				}
			}
	
			var first = function(){
				currentItem = 0;

				animateDots();
				move();
			}
	
			var second = function(){
				currentItem = 1;
		
				animateDots();
				move();
			}
	
			var third = function(){
				currentItem = 2;
		
				animateDots();
				move();
			}
	
			return {
				init: init,
				next: next,
				previous: previous,
				start: start,
				stop: stop
			}
		})();

		$(document).ready(function(){
			Carousel.init();
		});
	</script>
<% end %>