config/routes.rb
IndieTheater::Application.routes.draw do
  devise_for :customers, :controllers => { :omniauth_callbacks => "customers/omniauth_callbacks" }
  devise_for :admins

  root :to => "pages#index"

  resources :pages, :only => [:index] 
  match '/about' => 'pages#about'
  match '/contact' => 'pages#contact'
  
  resources :customers
  resources :admins, :except => [:show]
  resources :movies
  resources :showtimes, :only => [:index, :show]
  resources :orders, :only => [:show, :create, :destroy]
  resources :cart_items, :only => [:create, :destroy]
  resources :reviews, :except => [:index, :show]
  resources :comments
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IndieTheater</title>
	<link href='http://fonts.googleapis.com/css?family=Average+Sans' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header class="header">
		<div class="header-wrap group">
			
			<h1 class="header-logo">
				<%= link_to "Indie Theater", root_url %>
			</h1>
			
			<nav class="header-nav">
				<ul class="group">
					<li><%= link_to "Showtimes", showtimes_url %></li>
					<li><%= link_to "Movies", movies_url %></li>
					<li><%= link_to "Contact", contact_url %></li>
					<li><%= link_to "About", about_url %></li>
					<li><%= login_logout_link %></li>
				</ul>
			</nav>
			
		</div>
	  <p class="notice"><%= notice %></p>
	  <p class="alert"><%= alert %></p>
	</header>

<%= yield %>

<footer class="footer group">
	
	<small class="footer-copy">
		&copy; 2013 Indie Theater. All rights reserved.
	</small>
		
	<nav class="footer-links">
		<ul class="group">
			<li><%= link_to "Created by James Pothen", "http://www.jamespothen.com", :target => "blank" %></li>
		</ul>
	</nav>
	
</footer>
</body>
</html>